name: CI
on: [push, pull_request]

jobs:
  cuda_test:
    name: CUDA Test
    runs-on: ubuntu-latest
    container: nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04
    steps:
    - uses: actions/checkout@master
    - run: nvcc
    
