name: CI
on: [push, pull_request]

jobs:
  cuda_test:
    name: CUDA Test
    runs-on: ubuntu-latest
    container: nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04
    steps:
    - uses: actions/checkout@master
    - run: nvcc --version # cuda install check
    - run: apt-get update && apt-get install -y curl
    - name: Install rustup
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - name: Install Rust (rustup)
      run: source $HOME/.cargo/env && rustup update stable --no-self-update && rustup default stable
      shell: bash
    - name: rustup target
      run: source $HOME/.cargo/env && rustup target add x86_64-unknown-linux-gnu
      shell: bash
    - name: Install g++-multilib
      run: |
        set -e
        # Remove the ubuntu-toolchain-r/test PPA, which is added by default.
        # Some packages were removed, and this is causing the g++multilib
        # install to fail. Similar issue:
        # https://github.com/scikit-learn/scikit-learn/issues/13928.
        sudo add-apt-repository --remove ppa:ubuntu-toolchain-r/test
        sudo apt-get install g++-multilib
      if: matrix.build == 'linux32'
    - name: cargo build
      run: source $HOME/.cargo/env && cargo build
    - name: cargo test 
      run: source $HOME/.cargo/env && cargo test 
    - name: cargo test --features parallel
      run: source $HOME/.cargo/env && cargo test --features parallel
    - name: cargo test --manifest-path cc-test/Cargo.toml --target x86_64-unknown-linux-gnu
      run: source $HOME/.cargo/env && cargo test --manifest-path cc-test/Cargo.toml --target x86_64-unknown-linux-gnu
    - name: cargo test --manifest-path cc-test/Cargo.toml --target x86_64-unknown-linux-gnu --features parallel
      run: source $HOME/.cargo/env && cargo test --manifest-path cc-test/Cargo.toml --target x86_64-unknown-linux-gnu --features parallel
    - name: cargo test --manifest-path cc-test/Cargo.toml --target x86_64-unknown-linux-gnu --release
      run: source $HOME/.cargo/env && cargo test --manifest-path cc-test/Cargo.toml --target x86_64-unknown-linux-gnu --release
